baseURL = "https://vedikabang.com/"
languageCode = "en-us"
title = "Vedika's Site"
theme = "archie"
copyright = "© Vedika Bang"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="auto"
    useCDN=false
    mathjax = true
	katex = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/VedikaBang"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/vedikabang/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
